function initGalleryImages() {
	const fileNames = [
		'Beer Olympics-100.jpg',
		'Beer Olympics-104.jpg',
		'Beer Olympics-105.jpg',
		'Beer Olympics-106.jpg',
		'Beer Olympics-107.jpg',
		'Beer Olympics-109.jpg',
		'Beer Olympics-110.jpg',
		'Beer Olympics-113.jpg',
		'Beer Olympics-116.jpg',
		'Beer Olympics-118.jpg',
		'Beer Olympics-119.jpg',
		'Beer Olympics-121.jpg',
		'Beer Olympics-123.jpg',
		'Beer Olympics-125.jpg',
		'Beer Olympics-128.jpg',
		'Beer Olympics-129.jpg',
		'Beer Olympics-13.jpg',
		'Beer Olympics-133.jpg',
		'Beer Olympics-134.jpg',
		'Beer Olympics-14.jpg',
		'Beer Olympics-140.jpg',
		'Beer Olympics-142.jpg',
		'Beer Olympics-145.jpg',
		'Beer Olympics-150.jpg',
		'Beer Olympics-151.jpg',
		'Beer Olympics-157.jpg',
		'Beer Olympics-16.jpg',
		'Beer Olympics-160.jpg',
		'Beer Olympics-163.jpg',
		'Beer Olympics-165.jpg',
		'Beer Olympics-168.jpg',
		'Beer Olympics-17.jpg',
		'Beer Olympics-173.jpg',
		'Beer Olympics-178.jpg',
		'Beer Olympics-181.jpg',
		'Beer Olympics-185.jpg',
		'Beer Olympics-190.jpg',
		'Beer Olympics-191.jpg',
		'Beer Olympics-195.jpg',
		'Beer Olympics-196.jpg',
		'Beer Olympics-201.jpg',
		'Beer Olympics-202.jpg',
		'Beer Olympics-205.jpg',
		'Beer Olympics-207.jpg',
		'Beer Olympics-209.jpg',
		'Beer Olympics-21.jpg',
		'Beer Olympics-215.jpg',
		'Beer Olympics-216.jpg',
		'Beer Olympics-218.jpg',
		'Beer Olympics-221.jpg',
		'Beer Olympics-26.jpg',
		'Beer Olympics-28.jpg',
		'Beer Olympics-3.jpg',
		'Beer Olympics-30.jpg',
		'Beer Olympics-36.jpg',
		'Beer Olympics-38.jpg',
		'Beer Olympics-39.jpg',
		'Beer Olympics-4.jpg',
		'Beer Olympics-41.jpg',
		'Beer Olympics-44.jpg',
		'Beer Olympics-48.jpg',
		'Beer Olympics-51.jpg',
		'Beer Olympics-57.jpg',
		'Beer Olympics-64.jpg',
		'Beer Olympics-67.jpg',
		'Beer Olympics-69.jpg',
		'Beer Olympics-7.jpg',
		'Beer Olympics-70.jpg',
		'Beer Olympics-73.jpg',
		'Beer Olympics-74.jpg',
		'Beer Olympics-77.jpg',
		'Beer Olympics-78.jpg',
		'Beer Olympics-79.jpg',
		'Beer Olympics-82.jpg',
		'Beer Olympics-84.jpg',
		'Beer Olympics-85.jpg',
		'Beer Olympics-87.jpg',
		'Beer Olympics-88.jpg',
		'Beer Olympics-89.jpg',
		'Beer Olympics-9.jpg',
		'Beer Olympics-91.jpg',
		'Beer Olympics-92.jpg',
		'Beer Olympics-93.jpg',
		'Beer Olympics-95.jpg',
		'Beer Olympics-97.jpg',
		'Beer Olympics.jpg',
		'image00001.jpeg',
		'image00002.jpeg',
		'image00005.jpeg',
		'image00016.jpeg',
		'image00017.jpeg',
		'image00024.jpeg',
		'image00028.jpeg',
		'image00032.jpeg',
		'possible1.jpg',
		'possible2.jpg',
		'possible3.jpg',
		'possible4.jpg',
		'possible5.jpg',
		'possible6.jpg'
	];
	const galleryContainer = document.querySelector('.gallery');

	fileNames.forEach(file => {
		galleryContainer.innerHTML += `<img src="./media/gallery/${file}" />`;
	});
}

initGalleryImages();
